<?php
/*
 * @author Cezar Jr. Souza <cezar08@unochapeco.edu.br>
 * 
 * @params array $breadcrumbs, string $head, Zend/Form $form, array $tableIndex
 * @retrun void 
 * Template para gerar formulários
 */
?>

<span class="breadcrumbs">
    <a href="">Você está aqui: </a>
    <!--Link de Breadcumbs-->

    <?php
    $keys = array_keys($this->breadcrumbs);
    $endKey = end($keys);
    foreach ($this->breadcrumbs as $chave => $breadcrumb) {
        if ($breadcrumb['url'] == '#')
            $urlBreadcrumb = '#';
        else
            $urlBreadcrumb = BASE_URL . $breadcrumb['url'];
        ?>
        <a href="<?php echo $urlBreadcrumb; ?>" title="<?php echo $breadcrumb['title']; ?>"><?php echo $breadcrumb['text']; ?></a>
        <!--Divisor do Link de Breadcumbs-->
        <?php if ($endKey != $chave) { ?>
            <img src="<?php echo BASE_URL; ?>/images/breadcrumbs.png" width="6" height="9" alt=">" />
            <?php
        }
    }
    ?>
</span>

<h2>   
    <span><?php echo $this->head; ?></span>
</h2>

<br><br>

<div class="links_head">
    <?php
    if ($this->headLinks) {
        ?>
        <div class="clearfix">
            <?php
            foreach ($this->headLinks as $link) {
                echo $link;
            }
            ?>
        </div>
        <?php
    }
    ?>
</div>


<!-- Botão Inserir Novo --> 
<?php if ($this->newButton) { ?>
    <div class="clearfix">
        <div class="btns">
            <a class="btn submit" href="<?php echo BASE_URL . $this->newButton['href']; ?>" title="<?php echo $this->newButton['title']; ?>"><?php echo $this->newButton['text']; ?></a> 
        </div>

    </div> 
<?php } ?>
<?php
if ($this->formSearch) {  
    echo $this->form()->openTag($this->formSearch);
    echo "<div style='width:300px';'>";
    echo $this->formCollection($this->formSearch);
    echo "</div>";
    echo $this->form()->closeTag($this->formSearch);
}
?>

<?php
if ($this->dataPagination->getCurrentItemCount() > 0) {
    if ($this->gridForm) {
        if ($this->action != '')
            $this->action = BASE_URL . $this->action;
        echo "<form method='POST' action='" . $this->action . "' name='gridForm' id='gridForm'><br><br>";
    }
    ?>
    <table class="datatable">
        <!--
    Cabeçálho da tabela com os títulos.
    É nas celulas de título que se definem as larguras das colunas para
    formatar a tabela. Pode-se utilizar valor fixo ou porcentagem.
    Tanto para as celulas de títulos quanto para as de dados, pode-se
    definir a classe "center" para centralizar seu conteúdo.
        -->

        <thead>
            <tr>
                <?php
                foreach ($this->tableIndex as $th) {
                    if (isset($th['tableHead']['attribs']))
                        $attributes = $th['tableHead']['attribs'];
                    else
                        $attributes = '';
                    ?>

                    <th <?php echo $attributes; ?>><?php echo $th['tableHead']['text']; ?></th>

                <?php } ?>
            </tr>
        </thead>


        <!--Dados da tabela-->
        <tbody>
            <?php
            if (!$this->id_update)
                $this->id_update = 'id';
            if (!$this->id_delete)
                $this->id_delete = 'id';

            $id_update = $this->id_update;
            $id_delete = $this->id_delete;

            foreach ($this->dataPagination as $pagination) {
                ?>
                <tr>
                    <?php foreach ($this->tableIndex as $ti) {
                        ?>

                        <td><?php
                            if ($ti['collumn']['text'] == "checkbox") {

                                echo "<input type='checkbox' name='vagas[]' value='$pagination[id]' />";
                            } else {

                                if (is_object($pagination[$ti['collumn']['text']])) {
                                    if (get_class($pagination[$ti['collumn']['text']]) == 'DateTime') {
                                        echo $pagination[$ti['collumn']['text']]->format('d/m/Y');
                                    }
                                } else {

                                    echo $pagination[$ti['collumn']['text']];
                                }
                            }
                            ?></td>
                    <?php } ?>
                    <td >
                        <?php if ($this->urlUpdate) { ?>
                            <a href="<?php echo BASE_URL . $this->urlUpdate . '/' . $this->id_update . '/' . $pagination[$this->id_update]; ?>" class="btn" title="Editar">
                                <span class="ui-icon ui-icon-pencil"></span>
                            </a>
                        <?php } ?>

                        <?php
                        if ($this->addIcon) {
                            foreach ($this->addIcon as $icon) {
                                ?>
                                <a href="<?php echo BASE_URL . $icon['url'] . '/id/' . $pagination['id']; ?>"  class="btn" title="<?php echo $icon['title']; ?>">
                                    <span class="<?php echo $icon['class']; ?>"></span>
                                </a>
                                <?php
                            }
                        }
                        ?>
                        <?php if ($this->urlDelete) { ?>
                            <a href="<?php echo BASE_URL . $this->urlDelete . '/' . $this->id_delete . '/' . $pagination[$this->id_delete]; ?>" rel="confirmation" class="btn" title="Deseja realmente excluir este registro?">
                                <span class="ui-icon ui-icon-circle-close"></span>
                            </a>
                        <?php } ?>

                        <?php if ($this->urlPdf) { ?>
                            <a  href="<?php echo BASE_URL . $this->urlPdf . '/id/' . $pagination['id']; ?>" class="btn" title="Gerar pdf">
                                <span class="ui-icon ui-icon-document"></span>
                            </a>
                        <?php } ?>                                                                          
                    </td>

                </tr>
            <?php } ?>
        </tbody>


    </table>


    <div id="paginator">
        <?php
        echo $this->paginationControl($this->dataPagination, 'Sliding', '/partials/paginator/control.phtml');
        ?>
    </div>

    <?php
    if ($this->gridForm) {
        echo "<input type='submit' class='btn submit' value='" . $this->submit . "' />" . $this->buttonForm .
        "</form><br>
            ";
    }
} else {
    echo "<div style='margin-top: 100px; margin-botton: 50px; text-align: center;'><label>Nenhum registro encontrado.</label></div>";
}
?>


<div id="dialog" title="Confirmação" >

</div>
<script type="text/javascript">
    $("#dialog").dialog({
        autoOpen: false,
        modal: true,
        buttons: {
            "Confirmar": function() {

                $(location).attr('href', href_confirmation);
            },
            "Cancelar": function() {
                $(this).dialog("close");
            }
        }
    });

    $(".btn").on("click", function(e) {
        if ($(this).attr('rel') == 'confirmation') {
            $('#dialog').html($(this).attr('title'))
            e.preventDefault();
            href_confirmation = $(this).attr('href');
            $("#dialog").dialog("open");
        }
    });//
</script>
