<!-- start:main -->
<div id="main">
    <div class="container">
        <div class="col-lg-8 col-md-8">
            <!-- start:single content -->
            <div id="main-single-content">
                <?php foreach ($posts as $post) { ?>
                <?php
                    $comentarios = $em->getRepository('Main\Entity\Comentario')
                            ->findBy(array('post' => $post->getId()));
                ?>
                    <div class="content-single">
                        <h2><?= $post->getTitulo(); ?></h2>
                        <div class="tag">
                            <p>	
                                <span><i class="fa fa-user" data-original-title="" title=""></i> 
                                    <a href="/main/index/pagina/id/<?= $post->getId(); ?>"><?= $post->getUsuario()->getNome(); ?></a>
                                </span> 
                                <i class="fa fa-circle" data-original-title="" title=""></i> 
                                <span><i class="fa fa-calendar" data-original-title="" title=""></i> 
                                    <a href="#"><?= $post->getData()->format('d/m/Y'); ?></a>
                                </span>
                                <span><i class="fa fa-calendar" data-original-title="" title=""></i> 
                                    <a href="#"><?php echo sizeof($comentarios) . " Comentarios"; ?></a>
                                </span>

                            </p>
                        </div>
                        <div class="hr-single"></div>
                        <p><?= $post->getMinText(); ?></p>
                        <input type="button" class="btn btn-primary" value="Leia Mais" 
                               onclick="window.location = '/main/index/pagina/id/<?= $post->getId(); ?>';">
                        <div class="hr-single"></div> 
                    </div>
                <?php } ?>
            </div>
            <div class="col-lg-12 col-md-12">
                
                <?php
            echo $this->paginationControl(
                    $posts, 'sliding', array('partials/paginator.phtml', 'Main'), 
                    array(
                    'route' => 'index_paginacao'
                    )
            );
            ?>
            </div> 
            <!-- end:single content -->
        </div>
        <div class="col-lg-4 col-md-4">
            <!-- start:sidebar -->
            <div id="sidebar">
                <!-- start:widget recent post -->
                <div class="widget-sidebar">
                    <h3 class="title-widget-sidebar">
                        // BUSCA
                    </h3>
                    <div class="content-widget-sidebar">
                        <form action="" method="post" class="form-inline">
                            <div class="form-group"> 
                                <input class="form-control" type="text" name="search" placeholder="Buscar" />
                            </div>
                            <input type="submit" class="btn btn-success" value="Buscar" />
                        </form>
                    </div>
                </div>
                <!-- end:widget recent post -->

            </div>
            <!-- end:sidebar -->
        </div>
    </div>
</div>