<!-- start:main -->
<div id="main">
    <div class="container">
        <div class="col-lg-8 col-md-8">
            <!-- start:single content -->
            <div id="main-single-content">
                <div class="content-single">
                    <h2>Niki Postingan Sing Kepisan Njeh, Perdana Ngoten</h2>
                    <div class="tag">
                        <p>	
                            <span><i class="fa fa-user" data-original-title="" title=""></i> <a href="#">Admin</a></span> 
                            <i class="fa fa-circle" data-original-title="" title=""></i> 
                            <span><i class="fa fa-calendar" data-original-title="" title=""></i> <a href="#">Juni, 30 2014</a></span>
                            
                        </p>
                    </div>
                    <div class="hr-single"></div>
                    <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Maecenas euismod diam at commodo sagittis. Nam id molestie velit. Nunc id nisl tristique, dapibus tellus quis, dictum metus. Pellentesque id imperdiet est. Maecenas adipiscing dui at enim placerat hendrerit. Curabitur pulvinar fermentum ante id bibendum. Etiam est sem, pharetra in luctus quis, tempor facilisis urna. Etiam ullamcorper dictum elit sit amet hendrerit. Donec porta mauris a est rhoncus pharetra.</p>
                    <p>Mauris pellentesque sem sem, sit amet faucibus purus venenatis id. Ut vitae risus eleifend, tristique elit vitae, rhoncus sapien. Nunc ipsum lacus, tincidunt et cursus sit amet, gravida auctor risus. Praesent quam tellus, fringilla in ante eu, euismod euismod orci. Aenean a tincidunt leo, lobortis vulputate neque. Pellentesque faucibus dignissim est consequat ultrices. Quisque elementum dolor vel posuere auctor. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Mauris dictum magna quis dolor imperdiet vestibulum. Proin ultricies malesuada diam id gravida. Aenean commodo aliquet gravida. Donec bibendum non libero id tincidunt.</p>
                    <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Maecenas euismod diam at commodo sagittis. Nam id molestie velit. Nunc id nisl tristique, dapibus tellus quis, dictum metus. Pellentesque id imperdiet est. Maecenas adipiscing dui at enim placerat hendrerit. Curabitur pulvinar fermentum ante id bibendum. Etiam est sem, pharetra in luctus quis, tempor facilisis urna. Etiam ullamcorper dictum elit sit amet hendrerit. Donec porta mauris a est rhoncus pharetra.</p>
                    <p>Mauris pellentesque sem sem, sit amet faucibus purus venenatis id. Ut vitae risus eleifend, tristique elit vitae, rhoncus sapien. Nunc ipsum lacus, tincidunt et cursus sit amet, gravida auctor risus. Praesent quam tellus, fringilla in ante eu, euismod euismod orci. Aenean a tincidunt leo, lobortis vulputate neque. Pellentesque faucibus dignissim est consequat ultrices. Quisque elementum dolor vel posuere auctor. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Mauris dictum magna quis dolor imperdiet vestibulum. Proin ultricies malesuada diam id gravida. Aenean commodo aliquet gravida. Donec bibendum non libero id tincidunt.</p>
                    <div class="hr-single"></div>
                    <!-- start:comments -->
                    <div id="comments-list">
                        <!-- start:comments list -->
                        <div class="comment">
                            <h3>Comentários</h3>
                            <ul class="comments">
                                <li>
                                    <img src="../../img/user.jpg">
                                    <div class="post-comments">
                                        <p class="meta">Juni 30, 2014 <a href="#">Admin</a> says : <i class="pull-right"></i></p>
                                        <p>
                                            Lorem ipsum dolor sit amet, consectetur adipiscing elit.
                                            Etiam a sapien odio, sit amet
                                        </p>
                                    </div>
                                </li> 
                            </ul>
                        </div>
                        <!-- end:comments list -->
                        <!-- start:form comment -->
                        <div class="form-comment">
                            <h3>Comente você também</h3>
                            <form role="form">
                                <div class="row">
                                    <div class="form-group col-md-12">
                                        <input class="form-control input-lg" placeholder="E-mail...">
                                    </div> 
                                    <div class="form-group col-md-12">
                                        <textarea class="form-control" rows="10" placeholder="Mensagem..."></textarea>
                                    </div>
                                    <div class="form-group col-md-12">
                                        <button class="btn btn-lg btn-default btn-block">Enviar</button>
                                    </div>
                                </div>
                            </form>
                        </div>
                        <!-- end:form comment -->
                    </div>
                    <!-- end:comments -->
                </div>
            </div>
            <!-- end:single content -->
        </div>
        <div class="col-lg-4 col-md-4">
            <!-- start:sidebar -->
            <div id="sidebar">
                <!-- start:widget recent post -->
                <div class="widget-sidebar">
                    <h3 class="title-widget-sidebar">
                        // POSTS RECENTES
                    </h3>
                    <div class="content-widget-sidebar">
                        <ul> 
                            <li class="recent-post"> 
                                 <div class="thumbnail">
                                    <img src="../../img/thumbnail1.jpg" class="img-responsive">
                                </div>
                                <a href="#"><h5>Excepteur sint occaecat cupi non
                                        proident laborum.</h5></a>
                                <p><small><i class="fa fa-calendar"></i> 30 Juni 2014</small></p>
                            </li> 
                        </ul>
                    </div>
                </div>
                <!-- end:widget recent post -->

            </div>
            <!-- end:sidebar -->
        </div>
    </div>
</div>