<!-- start:main -->
<div id="main">
    <div class="container">
        <div class="col-lg-8 col-md-8">
            <!-- start:single content -->
            <?php  foreach ($posts as $post) { ?>
            <div id="main-single-content">
                <div class="content-single">
                    <h2><?= $post->getTitulo(); ?></h2>
                    <div class="tag">
                        <p>	
                            <span><i class="fa fa-user" data-original-title="" title=""></i> <a href="#"><?= $post->getUsuario()->getNome(); ?></a></span> 
                            <i class="fa fa-circle" data-original-title="" title=""></i> 
                            <span><i class="fa fa-calendar" data-original-title="" title=""></i> <a href="#"><?= $post->getData()->format('d/m/Y'); ?></a></span>
                            
                        </p>
                    </div>
                    <div class="hr-single"></div>
                    <p><?= $post->getPostComp(); ?></p>
                    <div class="hr-single"></div>
                    <!-- start:comments -->
                    <div id="comments-list">
                        <!-- start:comments list -->
                        <div class="comment">
                            <h3>Comentários</h3>
                            <ul class="comments">
                                <?php foreach ($comentarios as $comentario) { ?>
                                <li>
                                    <img src="../../../../img/user.jpg">
                                    <div class="post-comments">
                                        <p class="meta"> <a href="#"><?= $comentario['email']; ?></a> Disse : <i class="pull-right"></i></p>
                                        <p>
                                            <?= $comentario['comentario']; ?>
                                        </p>
                                    </div>
                                </li> 
                                <?php } ?>
                            </ul> 
                        </div>
                        <!-- end:comments list -->
                        <!-- start:form comment -->
                        <div class="form-comment">
                            <h3>Comente você também</h3>
                            <form action="/main/comentarios/save" method="post">
                                <div class="row">
                                    <input type="hidden" name="post" id="post" value="<?= $post->getId(); ?>">
                                    <div class="form-group col-md-12">
                                        <input class="form-control input-lg" name="email" id="email" placeholder="E-mail...">
                                    </div> 
                                    <div class="form-group col-md-12">
                                        <textarea class="form-control" rows="10" name="comentario" id="comentario" placeholder="Mensagem..."></textarea>
                                    </div>
                                    <div class="form-group col-md-12">
                                        <button class="btn btn-lg btn-default btn-block">Enviar</button>
                                    </div>
                                </div>
                            </form>
                        </div>
                        <!-- end:form comment -->
                    </div>
                    <!-- end:comments -->
                </div>
            </div>
            <?php } ?>
            <!-- end:single content -->
        </div>
        <div class="col-lg-4 col-md-4">
            <!-- start:sidebar -->
            <div id="sidebar">
                <!-- start:widget recent post -->
                <div class="widget-sidebar">
                    <h3 class="title-widget-sidebar">
                        // BUSCA
                    </h3>
                    <div class="content-widget-sidebar">
                        <form action="" method="post" class="form-inline">
                            <div class="form-group"> 
                                <input class="form-control" type="text" name="search" placeholder="Buscar" />
                            </div>
                            <input type="submit" class="btn btn-success" value="Buscar" />
                        </form>
                    </div>
                </div>
                <!-- end:widget recent post -->

            </div>
            <!-- end:sidebar -->
        </div>
    </div>
</div>