<!-- start:main -->
<div id="main">
    <div class="container">
        <div class="col-lg-8 col-md-8">
            <!-- start:single content -->
            <?php  foreach($comentarios as $key => $comentario) { ?>

            <div id="main-single-content">
                <div class="content-single">
                    <h2>Niki Postingan Sing Kepisan Njeh, Perdana Ngoten</h2>
                    <div class="tag">
                        <p>	
                            <span><i class="fa fa-user" data-original-title="" title=""></i> <a href="#">Admin</a></span> 
                            <i class="fa fa-circle" data-original-title="" title=""></i> 
                            <span><i class="fa fa-calendar" data-original-title="" title=""></i> <a href="#">comments-></a></span>

                        </p>
                    </div>
                    <div class="hr-single"></div>
                    <p>
                        <?php  echo $comentario->getComentario() ?>
                    </p>
                    <div class="hr-single"></div> 
                </div>
                    
            </div>
            <?php  } ?>
//

            <div class="col-lg-12 col-md-12">
                            <div class="text-center">
                                <ul class="pagination">
                                    <li><a href="#">&laquo;</a></li>
                                    <li><a href="#">1</a></li>
                                    <li><a href="#">2</a></li>
                                    <li><a href="#">3</a></li>
                                    <li><a href="#">4</a></li>
                                    <li><a href="#">5</a></li>
                                    <li><a href="#">&raquo;</a></li>
                                </ul>
                            </div>
                        </div> 
            <!-- end:single content -->
        </div>
        <div class="col-lg-4 col-md-4">
            <!-- start:sidebar -->
            <div id="sidebar">
                <!-- start:widget recent post -->
                <div class="widget-sidebar">
                    <h3 class="title-widget-sidebar">
                        // POSTS RECENTES
                    </h3>
                    <div class="content-widget-sidebar">
                        <ul> 
                            <li class="recent-post"> 
                                 <div class="thumbnail">
                                    <img src="../../img/thumbnail1.jpg" class="img-responsive">
                                </div>
                                <a href="#"><h5>Excepteur sint occaecat cupi non
                                        proident laborum.</h5></a>
                                <p><small><i class="fa fa-calendar"></i> 30 Juni 2014</small></p>
                            </li> 
                        </ul>
                    </div>
                </div>
                <!-- end:widget recent post -->

            </div>
            <!-- end:sidebar -->
        </div>
    </div>
</div>