<button class="btn btn-success" onclick="location.href = '/admin/usuarios/save'">Novo Usuario</button>
<br>
<br>
<br>
<div class="panel panel-default">
    <div class="panel-body">
        <table class="table">
            <thead>
                <tr>
                    <td>Id</td>
                    <td>Nome</td>
                    <td>Editar</td>
                    <td>Excluir</td>
                </tr>
            </thead>
            <tbody>
                <?php foreach ($usuarios as $usuario) {
                    ?>
                    <tr>
                        <td>
                            <?php echo $usuario->getId(); ?>
                        </td>
                        <td>
                            <?php echo $usuario->getNome(); ?>
                        </td>
                        <td>
                            <a href="/admin/usuarios/save/id/<?php echo $usuario->getId(); ?>">Editar</a>
                        </td>
                        <td>
                            <a href="/admin/usuarios/delete/id/<?php echo $usuario->getId(); ?>">Excluir</a>
                        </td>
                    </tr>
                <?php }
                ?>
            </tbody>
    
</table>
</div>

<script type="text/javascript" src="/js/maskedinput.min.js"></script>
<script>
jQuery(function($){
       $("#data_nasc").mask("99/99/9999");
});
</script>
