<div class="panel panel-default">
    <div class="panel-body" style="width: 500px;">
      <?php
        echo $this->form()->openTag($form); 
    ?>
    <div>
        <?php echo $form->get('nome')->getLabel(); ?>
    </div>
    <div class="input-xlarge">
        <?php echo $this->formInput($form->get('nome')); ?>
    </div> 
    <div>
        <?php echo $form->get('email')->getLabel(); ?>
    </div>
    <div class="input-xlarge">
        <?php echo $this->formInput($form->get('email')); ?>
    </div> 
    <div>
        <?php echo $form->get('data_nasc')->getLabel(); ?>
    </div>
    <div class="input-xlarge">
        <?php echo $this->formInput($form->get('data_nasc')); ?>
    </div> 
    <div>
        <?php echo $form->get('perfil')->getLabel(); ?>
    </div>
    <div class="input-xlarge">
        <?php echo $this->formSelect($form->get('role')); ?>
    </div> 
    <div>
        <?php echo $form->get('perfil')->getLabel(); ?>
    </div>
    <div class="input-xlarge">
        <?php echo $this->formInput($form->get('perfil')); ?>
    </div> 
    <div>
        <?php echo $form->get('login')->getLabel(); ?>
    </div>
    <div class="input-xlarge">
        <?php echo $this->formInput($form->get('login')); ?>
    </div> 
    <div>
        <?php echo $form->get('senha')->getLabel(); ?>
    </div>
    <div class="input-xlarge">
        <?php echo $this->formInput($form->get('senha')); ?>
    </div> 
    <br>
    <div class="input-group">
        <?php echo $this->formSubmit($form->get('submit')); ?>
    </div> 
    <?php
        echo $this->form()->closeTag();
    ?>
  </div>
</div>
