<style>   
    h2{
        margin-bottom: 50px;
    }
    .ui-widget-header 
    {
        background: #809595;
    }   

    .ui-tabs .ui-tabs-panel {
        display: block;
        clear: both;
        padding: 10px;
    }

    .ui-tabs .ui-tabs-nav li a {
        display: block;
        padding: 10px 20px;
        background: #FFFFFF;
        border: 2px #FFFFFF solid;
        border-bottom-color: #FFFFFF;
        outline: none;
    }

    .ui-tabs .ui-tabs-nav li.ui-tabs-selected a {
        padding: 10px 20px 12px 20px;
        background: #FFFFFF;
        border-bottom-style: none;
    }

</style>
<script>

    $(function() {
        $("#tabs").tabs();
        $('#tabs').bind('tabsshow', function(event, ui) {
            $('#tabs').css('background-color');
        });
    });
</script> 
<span class="breadcrumbs">
    <a href="">Você está aqui: </a>
    <!--Link de Breadcumbs-->

    <?php
    $keys = array_keys($this->breadcrumbs);
    $endKey = end($keys);
    foreach ($this->breadcrumbs as $chave => $breadcrumb) {
        if ($breadcrumb['url'] == '#')
            $urlBreadcrumb = '#';
        else
            $urlBreadcrumb = BASE_URL . $breadcrumb['url'];
        ?>
        <a href="<?php echo $urlBreadcrumb; ?>" title="<?php echo $breadcrumb['title']; ?>"><?php echo $breadcrumb['text']; ?></a>
        <!--Divisor do Link de Breadcumbs-->
        <?php if ($endKey != $chave) { ?>
            <img src="<?php echo BASE_URL; ?>/images/breadcrumbs.png" width="6" height="9" alt=">" />
            <?php
        }
    }
    ?>
</span>

<h2>   
    <span><?php echo $this->head; ?></span>
</h2>

<div id="tabs">
    <ul>
        <?php foreach ($this->abas as $aba) {
            ?>
            <li><a href="<?php echo $aba['href']; ?>"><?php echo $aba['text']; ?></a></li>                
        <?php }
        ?>
    </ul>

    <?php foreach ($this->divs as $div) {
        ?>
        <div id="<?php echo $div['id'] ?>">
            <div>
                <p>
                    <?php
                    echo "<table class='datatable'>";
                    if (isset($div['tableHead'])) {
                        foreach ($div['tableHead'] as $th) {
                            echo "<th>$th</th>";
                        }
                    }
                    foreach ($div['element'] as $element) {
                        echo "<tr>";
                        if (!is_array($element['value'])) {
                            echo '<td>' . $element['label'] . '</td><td> ' . $element['value'] . '</td>';
                        }else{
                            foreach($element['value'] as $v){
                                echo "<td>$v</td>";
                            }
                        }
                        if (isset($element['icon'])) {
                            foreach ($element['icon'] as $icon)
                                echo "<td>
                                    <a href='" . $icon['url'] . "' class='btn' title='" . $icon['title'] . "' >
                                        <span class=" . $icon['class'] . ">
                                        </span>
                                    </a></td>";
                        }
                        echo "</tr>";
                    }
                    echo '</table>';
                    ?>

                </p>

            </div>

        </div>
    <?php } ?>

</div>
<div>
    <input style='margin-left: 1%;' type="button" class="btn" value="Voltar" onclick="location.href = '<?php echo BASE_URL . $this->back; ?>'" />

</div>
<br><br>
