<?php
if ($this->dados) {
    foreach ($this->dados as $dado) {
        $checked = '';
        foreach ($this->dados_selecionadas as $dado_sel) {
            if ($dado_sel[$this->idColumnSelecionado] == $dado[$this->idColumn]) {
                $checked = 'checked';
                break;
            }
        }
        echo "<label><input $checked type='checkbox' name='$this->name[]' value='" . $dado[$this->idColumn] . "' />" . $dado[$this->descColumn] . "</label>";
    }
} else {
    ?>
    <div>

        <label for=""></label>
        <span class="info clearfix"><?php echo "<img src='/images/exclamacao_cyan.png' />" . $this->msg ?></span>

    </div>
<?php
}
exit;
?>