<?php echo $this->doctype(); ?>

<html lang="pt-br">
    <head>
        <meta charset="utf-8">
        <?php echo $this->headTitle('Café com leite blog')->setSeparator(' - ')->setAutoEscape(false) ?>

        <?php echo $this->headMeta()
            ->appendName('viewport', 'width=device-width, initial-scale=1.0')
            ->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
        ?>

        <!-- Le styles -->
        <?php echo $this->headLink(array('rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/img/favicon.ico'))
                        ->prependStylesheet($this->basePath('css/style.css'))
                        ->prependStylesheet($this->basePath('css/bootstrap-theme.min.css'))
                        ->prependStylesheet($this->basePath('css/bootstrap.min.css')) ?>

        <!-- Scripts -->
        <?php echo $this->headScript()
            ->prependFile($this->basePath('js/bootstrap.min.js'))
            ->prependFile($this->basePath('js/jquery.min.js'))
            ->prependFile($this->basePath('js/respond.min.js'), 'text/javascript', array('conditional' => 'lt IE 9',))
            ->prependFile($this->basePath('js/html5shiv.js'),   'text/javascript', array('conditional' => 'lt IE 9',))
        ; ?>

    </head>
    <body>
        <nav class="navbar navbar-default navbar-fixed-top" role="navigation">
            <div class="container">
                <div class="navbar-header">
                    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </button> 
                </div>
                <div class="collapse navbar-collapse">
                    <ul class="nav navbar-nav">
                        <li><a href="/main">Home</a></li> 
                    </ul>
                    <ul class="nav navbar-nav navbar-right">
                    
                        <?php $user = $this->session()->offsetGet('user'); ?>
                        <?php if ($user): ?>
                            <li><a>Bem vindo, <?php echo $user->getNome();?>.</a></li>
                        <?php if ($user-getPerfil == 'ADMIN') { ?>
                            <li><a href="/admin/index/opcoes">Menu de Opções</a></li>
                        <?php } ?>
                            <li><a href="/admin/login/logout">Clique para sair</a></li>
                        <?php else: ?>
                            <li><a href="/admin" target="_blank"><?php echo $this->translate('Entrar') ?></a></li>
                        <?php endif;?>
                    
                </div><!--/.nav-collapse -->
            </div>
        </nav>
        <div class="container">
            <!-- Msg Success -->

            <?php if ($this->flashMessenger()->getSuccessMessages()) { ?>
                <div  class="alert alert-success" role="alert">
                    <?php
                    foreach ($this->flashMessenger()->getSuccessMessages() as $msg) {
                        echo $msg;
                    }
                    ?>

                </div>
            <?php } ?>
            <!-- Msg Error -->

            <?php if ($this->flashMessenger()->getErrorMessages()) { ?>
                <div class="alert alert-danger" role="alert">
                    <?php
                    foreach ($this->flashMessenger()->getErrorMessages() as $msg) {
                        echo $msg;
                    }
                    ?>
                </div>
            <?php } ?>

            <!-- Msg Warning -->

            <?php if ($this->flashMessenger()->getInfoMessages()) { ?>
                <div class="alert alert-warning" role="alert">
                    <?php
                    foreach ($this->flashMessenger()->getInfoMessages() as $msg) {
                        echo $msg;
                    }
                    ?>
                </div>
            <?php } ?>
            
            <?php echo $this->content; ?>
            <hr>
            <footer>
                <p>&copy; Café com leite blog. Todos os direitos reservados.</p>
            </footer>
        </div> <!-- /container -->
        <?php echo $this->inlineScript() ?>
    </body>
</html>
