<div class="wrapper">
    <form class="form-signin" method="post">       
        <h2 class="form-signin-heading">Acesso ao Admin</h2>
        <input type="text" class="form-control" name="login" placeholder="Login" required="" autofocus="" />
        <br>
        <input type="password" class="form-control" name="password" placeholder="Senha" required=""/>
        <br>
        <button class="btn btn-lg btn-primary btn-block" type="submit">Acessar</button>   
    </form>    
</div>
