<div class="wrapper">
    <form class="form-signin">       
        <h2 class="form-signin-heading">Escolha oque fazer</h2>
        <button name="btn-usuarios" class="btn btn-lg btn-primary btn-block" 
                onclick="window.location = '/admin/usuarios';"
                type="button">Usuarios</button> 
        <br>
        <button name="btn-posts" class="btn btn-lg btn-primary btn-block" 
                onclick="window.location = '/admin/posts';"
                type="button">Posts</button>
        <br>
        <button name="btn-Comentarios" class="btn btn-lg btn-primary btn-block"
                onclick="window.location = '/admin/comentarios';"
                type="button">Comentarios</button>   
    </form>
    
</div>
