<div class="wrapper">
    <form class="form-signin">       
        <h2 class="form-signin-heading">Acesse o blog</h2>
        <input type="text" class="form-control" name="login" placeholder="Login" required="" autofocus="" />
        <br>
        <input type="password" class="form-control" name="password" placeholder="Senha" required=""/>
        <br>
        <button class="btn btn-lg btn-primary btn-block" type="submit" onclick="http://localhost:8080/main" >Acessar</button>   
        <br>
        Ainda não possuí cadastro? <a href="/admin/usuarios">Cadastre-se!</a>
    </form>
    
</div>
