
<div class="wrapper">

<button class="btn btn-success" onclick="location.href = '/admin/posts/save'">Novo Post</button>
<br>
<br>
<br>
<div class="panel panel-default">
    <div class="panel-body">
        <table class="table">
            <thead>
                <tr>
                    <td>Id</td>
                    <td>Título</td>
                    <td>Data</td>
                    <td>Editar</td> 
                    <?php $user = $this->session()->offsetGet('user'); ?>
                    <?php if ($user->getPerfil() == 'ADMIN'): ?>
                        <td>Excluir</td>
                    <?php endif;?>
                    
                </tr>
            </thead>
            <tbody>
                <?php foreach ($posts as $post) {
                    
                    ?>
                    <tr>
                        <td>
                            <?php echo $post->getId();?>
                        </td>
                        <td>
                            <?php echo $post->getTitulo(); ?>
                        </td>
                        <td>
                            <?php echo $post->getData()->format('d/m/Y'); ?>
                        </td>
                        <td>
                            <a href="/admin/posts/save/id/<?php echo $post->getId(); ?>">Editar</a>
                        </td>
                        <?php if ($user->getPerfil() == 'ADMIN'): ?>
                        <td>
                            <a href="/admin/posts/delete/id/<?php echo $post->getId(); ?>">Excluir</a>
                        </td>
                        <?php endif;?> 
                    </tr>
                <?php } ?>
            </tbody>
</table>
</div>
</div>