<div class="panel panel-default">
    <div class="panel-body" style="width: 500px;">
      <?php
        echo $this->form()->openTag($form); 
    ?>
        <?php echo $this->formHidden($form->get('id')); ?>
    <div>
        <?php echo $form->get('titulo')->getLabel(); ?>
    </div>
    <div class="input-xlarge">
        <?php echo $this->formInput($form->get('titulo')); ?>
    </div> 
    <div>
        <?php echo $form->get('minText')->getLabel(); ?>
    </div>
    <div class="input-xlarge">
        <?php echo $this->formTextarea($form->get('minText')); ?>
    </div> 
    <div>
        <?php echo $form->get('postComp')->getLabel(); ?>
    </div>
    <div class="input-xlarge">
        <?php echo $this->formTextarea($form->get('postComp')); ?>
    </div>  
    <?php $user = $this->session()->offsetGet('user'); ?>
    <?php if ($user->getPerfil() == 'ADMIN'): ?>
        <div class="input-xlarge">
            <?php echo $this->formCheckbox($form->get('ativo')); ?> <?php echo $form->get('ativo')->getLabel(); ?>
        </div> 
    <?php endif;?>
    <br>
    <div class="input-group">
        <?php echo $this->formSubmit($form->get('submit')); ?>
    </div>    
    <?php
        echo $this->form()->closeTag();
    ?>
  </div>
</div> 
