
<div id="tabs-forms">

    <ul>
        <?php foreach ($this->forms as $form) {
            ?>
            <li id="<?php echo $form['idAba']; ?>li"><a href="#<?php echo $form['idAba'] ?>" onclick="abas('#<?php echo $form['idAba'] ?>')"><?php echo $form['textoAba'] ?></a></li>

        <?php } ?>
    </ul>

    <form action="<?php echo $this->action ?>" method="<?php echo $this->method ?>" >

        <?php
                function Elementos($form){
                    
                $disableFieldset = '';
        foreach ($this->forms as $form) {

            echo '<fieldset ' . $disableFieldset . ' id="' . $form['idAba'] . '">';

            foreach ($form['elementosAdicionaisSuperior'] as $addSuperior) {
                echo '<div>';
                echo $addSuperior;
                echo '</div>';
            }
      
            if (array_key_exists('subForm', $form)) {

                foreach ($form['subForm'] as $subForm) {
                    foreach ($subForm->getElements() as $subElement) {
                        $type = $subElement->getAttribute('type');
                        if ($subElement->getLabel()) {
                            if ($type != 'button')
                                echo "<label>" . $subElement->getLabel() . "</label>";
                        }
                        switch ($type) {
                            case 'hidden':
                                echo $this->formHidden($subForm->get($subElement->getName()));
                                break;
                            case 'text':
                                echo $this->formText($subForm->get($subElement->getName()));
                                break;
                            case 'select':
                                echo $this->formSelect($subForm->get($subElement->getName()));
                                break;
                            case 'checkbox':
                                echo $this->formCheckbox($subForm->get($subElement->getName()));
                                break;
                            case 'radio':
                                echo $this->formRadio($subForm->get($subElement->getName()));
                                break;
                            case 'button':

                                echo $this->formButton($subForm->get($subElement->getName()));

                                break;

                            case 'textarea':
                                echo $this->formTextArea($subForm->get($subElement->getName()));
                                break;
                        }
                    }
                }
            }

            foreach ($form['form']->getElements() as $element) {
                echo '<div>';

                $type = $element->getAttribute('type');
                if ($element->getLabel()) {
                    if ($type != 'button')
                        echo "<label>" . $element->getLabel() . "</label>";
                }
                switch ($type) {
                    case 'hidden':
                        echo $this->formHidden($form['form']->get($element->getName()));
                        break;
                    case 'text':
                        echo $this->formInput($form['form']->get($element->getName()));
                        break;
                    case 'select':
                        echo $this->formSelect($form['form']->get($element->getName()));
                        break;
                    case 'checkbox':
                        echo $this->formCheckbox($form['form']->get($element->getName()));
                        break;
                    case 'radio':
                        echo $this->formRadio($form['form']->get($element->getName()));
                        break;
                    case 'button':
                        if ($element->getName() == 'cancelar') {
                            $cancelar = $this->formButton($form['form']->get($element->getName()));
                        } else {
                            echo $this->formButton($form['form']->get($element->getName()));
                        }
                        break;
                    case 'submit':
                        $submit = $this->formSubmit($form['form']->get($element->getName()));
                        break;
                    case 'textarea':
                        echo $this->formTextArea($form['form']->get($element->getName()));
                        break;
                }
            
         ?>

                <result class="ui-widget">
                    <div class="<?php echo $classWarning; ?>">
                        <span class="warning-result">

                        </span>
        <?php
        if (isset($messageErrorExib))
            echo "   <img src='/images/exclamacao.jpg'>   " . $messageErrorExib;
        ?>
                    </div>
                </result>
                        <?php
                        echo '</div>';
                    }
                    echo '</fieldset>';
                    $disableFieldset = 'style="display: none"';
                }
                }
                echo $submit;
                echo $cancelar;
                ?>
    </form>
</div>

<script>
            function abas(element) {
                $('#tabs-forms ul a').css('border', '1px solid #7F9393 ');
                $('#tabs-forms ul a').css('color', '#7F9393');

                $('fieldset').attr('style', 'display: none;');
                $(element).attr('style', 'display: block;');

                $(element + 'li a').attr('style', 'border: solid 2px #7F9393; color: #7F9393;');

            }
</script>
